#update.packages(ask = FALSE)
r = getOption("repos") 
r["CRAN"] = "https://cran.mi2.ai/"
options(repos = r)


install.packages("spDataLarge",dependencies=TRUE,repos='https://nowosad.github.io/drat/', type='source')
install.packages("RColorBrewer")
install.packages("maptools",dependencies=TRUE)

install.packages("sp",dependencies=TRUE)
install.packages("raster",dependencies=TRUE)

install.packages("mgcViz",dependencies=TRUE)
install.packages("writexl",dependencies=TRUE)
install.packages("readxl",dependencies=TRUE)
install.packages("openxlsx",dependencies=TRUE)
install.packages("rasterVis",dependencies=TRUE)
install.packages("spatstat",dependencies=TRUE)
install.packages("latticeExtra",dependencies=TRUE)
install.packages("deldir",dependencies=TRUE)
install.packages("dismo",dependencies=TRUE)
install.packages("fields",dependencies=TRUE)
install.packages("geosphere",dependencies=TRUE)
install.packages("RandomFields",dependencies=TRUE)
install.packages("randomForest",dependencies=TRUE)
install.packages("rpart",dependencies=TRUE)
install.packages("sf",dependencies=TRUE)
install.packages("spdep",dependencies=TRUE)
install.packages("XML",dependencies=TRUE)
install.packages("spData",dependencies=TRUE)
install.packages("spgwr",dependencies=TRUE)
install.packages("kernlab",dependencies=TRUE)
install.packages("Rwofost",dependencies=TRUE, repos='http://R-Forge.R-project.org')
install.packages("RStoolbox",dependencies=TRUE)
install.packages("landsat",dependencies=TRUE)
install.packages("hsdar",dependencies=TRUE)
devtools::install_github("hadley/devtools")
devtools::install_github("CIAT-DAPA/analogues")
devtools::install_github("palderman/dssatR")
devtools::install_github("agrobioinfoservices/climatrends", build_vignettes = TRUE)
#devtools::install_github("agrobioinfoservices/gosset", build_vignettes = TRUE)
#devtools::install_github("agrobioinfoservices/gdistance")
#devtools::install_github("agrobioinfoservices/ClimMobTools")
install.packages("vroom",dependencies=TRUE)
install.packages("future",dependencies=TRUE)
install.packages("furrr",dependencies=TRUE)
install.packages("doSNOW",dependencies=TRUE)
install.packages("earth",dependencies=TRUE)
install.packages("FactoMineR",dependencies=TRUE)
install.packages("parallelDist",dependencies=TRUE)
install.packages("terra",dependencies=TRUE)
install.packages("trend",dependencies=TRUE)
install.packages("climatrends",dependencies=TRUE)
install.packages("caretEnsemble",dependencies=TRUE)
install.packages("ggspatial",dependencies=TRUE)
install.packages("adehabitatHR",dependencies=TRUE)
install.packages("tcltk2",dependencies=TRUE)
install.packages("fastcluster",dependencies=TRUE)
install.packages("foreach",dependencies=TRUE)
install.packages("tidyverse",dependencies=TRUE)
install.packages("cluster",dependencies=TRUE)
install.packages("glue",dependencies=TRUE)
install.packages("pacman",dependencies=TRUE)
install.packages("purrr",dependencies=TRUE)
install.packages("fst",dependencies=TRUE)
install.packages("lubridate",dependencies=TRUE)
install.packages("sdm",dependencies=TRUE)
install.packages("distances",dependencies=TRUE)
install.packages("rlang",dependencies=TRUE)
install.packages("gdistance",dependencies=TRUE)
install.packages("caret",dependencies=TRUE)
install.packages("bindrcpp",dependencies=TRUE)
install.packages("proc",dependencies=TRUE)
install.packages("maxnet",dependencies=TRUE)
install.packages("usdm",dependencies=TRUE)
install.packages("tictoc",dependencies=TRUE)
install.packages("snow",dependencies=TRUE)
install.packages("gtools",dependencies=TRUE)
install.packages("domc",dependencies=TRUE)
install.packages("ade4",dependencies=TRUE)
install.packages("doParallel",dependencies=TRUE)
install.packages("adehabitatHR",dependencies=TRUE)
install.packages("doMC",dependencies=TRUE)
install.packages("caretEnsemble",dependencies=TRUE)
install.packages("proj4",dependencies=TRUE)
install.packages("RMAWGEN",dependencies=TRUE)
install.packages("meteor",dependencies=TRUE)
install.packages("mclust",dependencies=TRUE)
install.packages("fpc",dependencies=TRUE)
install.packages("Rquefts",dependencies=TRUE)
install.packages("reshape",dependencies=TRUE)
install.packages("DSSAT",dependencies=TRUE)
install.packages("Dasst",dependencies=TRUE)
install.packages("anytime",dependencies=TRUE)
#devtools::install_github("cropmodels/Recocrop")
#devtools::install_github("ropensci/rgbif")
#devtools::install_git('https://gitlab.croptrust.org/genesys-pgr/genesysr')
#remotes::install_github("reagro/agro")
#remotes::install_github("reagro/carobiner")
